### ISSUE TITLE
Include me

### ISSUE THREAD

**Issue by hannahahn1024** [ritot/ritot.github.io#1]
Hi,
I am a member of friendies who lives in California. I would like to be included on the map. Just because I’m on the other side of the country, it does not mean that I have ceased to exist.
Thanks :)

**Comment by ritotn** [comment]
Please let me know your coordinates in longitude and latitude (standard four decimals)

**Comment by hannahahn1024** [comment]
Longitude: -118.2435
Latitude: 34.2272

**Comment by ritotn** [comment]
There is now a Hannah button that takes you to your house, along with a Williams button that takes you back to campus

**Comment by hannahahn1024** [comment]
Thanks <3
